### ISSUE TITLE
[cd8s] Design Pattern 적용

### ISSUE THREAD

**Issue by BaeKY** [BaeKY/k8s-cicd#3]
> 디자인 패턴을 적용하여 코드의 재사용성을 높이고 보기좋게 만들어보자

**Comment by BaeKY** [comment]
## k8s.Chart의 Component 생성 순서
> 어떤 app을 k8s에 올리기 위해 필요한 `config-map`, `secret`, `deployment`, `service`가 있다고 가정
1. `configMap`, `secret` => App에 필요한 환경변수 혹은 변수들 저장되어있으므로 먼저 생성
2. `deployment` 생성 => App 구동
3. `service` 생성

## Builder Pattern
- k8s Manifest 파일들은 공통적으로 `apiVersion`, `metadata`, `kind`, `spec`을 가짐.
- `apiVersion`, `kind`의 경우 cdk8s의 클래스에 이미 정의되어 있음.
- `metadata`, `spec`에서 변동이 생김
- 다음과 같은 형태로 사용하고 싶음.
```Typescript
import { DeploymentBuilder, DeploymentSpecBuilder, DeploymentSpecTemplateBuilder } from '../libs'

const deploymentMetadata = { /* Metadata */ }
const deploymentTempalte = DeploymentSpecTemplateBuilder.start()
        .setMetadata(deploymentMetadata)
        .addTemplateSpecContainer(/* Template Spec Container OR Function which have builder as param */)
        .addTemplateSpecVolume(/* Tempalte Spec Volume OR Function which have builder as param */)
        .build()
const deploymentSpec = DeploymentSpecBuilder.start()
        .setReplicas(2)
        .setSelector(deploymentSelector)
        .setTemplate(deploymentTemplate)
        .build()
const exampeDeployment = DeploymentBuilder.start(chart, id, props)
        .setMetadata(deploymentMetadata)
        .setSpec(deploymentSpec) // or Function which have builder as param
        .build()
```

**Comment by BaeKY** [comment]
## 계획 변경
-  DeploymentBuilder, IngressBuilder 등 Component 별로 Bulider를 만들기에는 너무 많은 자원이 소모됨
- ComponentBuilder 라는 클래스 하나로 퉁치자

## App, Chart Builder
- 다음과 같이 사용한다.
```Typescript
  const props = { namespace: 'hello' }
  AppBuilder.start()
    .addChart(
      'b-chart',
      (_) => _.setProps(props)
        .addComponent('deployment', () => {
          const name = 'svelte-example'
          const labels = {
            'app.kubernetes.io/name': 'svelte-example',
            'app.kubernetes.io/component': 'app'
          }
          return ComponentBuilder.start(k8s.KubeDeployment, {
            metadata: {
              name,
              labels
            },
            spec: {
              selector: {
                matchLabels: labels
              },
              template: {
                metadata: {
                  name,
                  labels
                },
                spec: {
                  containers: [
                    {
                      name: 'main',
                      image: 'ghcr.io/baeky/svelte-example:0.0.1'
                    }
                  ],
                  imagePullSecrets: [{
                    name: 'ghcr-token'
                  }]
                }
              }
            }
          })
        })
    )
    .addChart('a-chart', (_) => _.setProps(props))
    .addChart('c-chart', (_) => _.setProps(props))
    .build()
    .synth()
```
- 위 부분에서 `addComponent` 2번째 인자 부분이 크므로 다음과 같이 파일을 나눠서 사용한다
```Typescript
// svelte-example.deployment.ts
export const deploymentSvelteExample = (): ComponentBuilder<k8s.KubeDeployment, k8s.KubeDeploymentProps> => {
  const name = 'svelte-example'
  const labels = {
    'app.kubernetes.io/name': 'svelte-example',
    'app.kubernetes.io/component': 'app'
  }
  return ComponentBuilder.start(k8s.KubeDeployment, {
    metadata: {
      name,
      labels
    },
    spec: {
      selector: {
        matchLabels: labels
      },
      template: {
        metadata: {
          name,
          labels
        },
        spec: {
          containers: [
            {
              name: 'main',
              image: 'ghcr.io/baeky/svelte-example:0.0.1'
            }
          ],
          imagePullSecrets: [{
            name: 'ghcr-token'
          }]
        }
      }
    }
  })
}


// index.ts
const props = { namespace: 'hello' }
AppBuilder.start()
  .addChart(
    'b-chart',
    (_) => _.setProps(props)
      .addComponent('deployment', deploymentSvelteExample())
  )
  .addChart('a-chart', (_) => _.setProps(props))
  .addChart('c-chart', (_) => _.setProps(props))
  .build()
  .synth()

```

**Comment by BaeKY** [comment]
## ingress-nginx-controller 추가
- cdk8s의 [`Include`](https://cdk8s.io/docs/latest/concepts/include/#include) 클래스를 사용하여 `yaml`형식으로 정의된 파일을 가져다 쓸수있음.
- 베어메탈에서 사용할 [ingress-nginx-controller](https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.5/deploy/static/provider/baremetal/deploy.yaml)를 Include를 사용하여 내 yaml에 추가한다

**Comment by BaeKY** [comment]
## K8S Component간의 의존성 관리
- `kubectl apply -f <YAML>`을 통해 배포할 때 yaml파일에 여러 component들이 포함되어있는 경우 위에서 아래로 순서대로 실행됨.
- 하지만 Component간의 의존성을 고려하여 배포하려고 할 때는 부모 Component가 생성이 완료되고 부모 Component에 의존하는 다른 Component들이 생성될 필요가 있음.
- 아래의 stackoverflow 이슈처럼 [InitContainer](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)로 보장이 가능하다고 하는데 알아보자

> https://stackoverflow.com/questions/49526564/specify-depends-on-in-kubernetes-deployment

**Comment by BaeKY** [comment]
## Chart 나누기
- ex) mosquitto-chart, redis-chart, svelte-example-chart

## TODO
- [ ] 폴더구조 개편
- [ ] ingress-nginx-controller-chart
- [ ] metal-lb-chart
- [ ] svelte-example-chart

**Comment by BaeKY** [comment]
## helm 추가
- cdk8s를 이용하여 helm 차트를 구성해본다.

## TODO
- [ ] Prometheus
- [ ] Grafana
